version: "3.7"
services:
  app-dev:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    container_name: app-dev
    command: npm run dev
    restart: always
    volumes:
      - ./src:/opt/app/src
      - ./documents:/opt/app/documents
      - ./swagger.yaml:/opt/app/swagger.yaml
    ports:
      - 127.0.0.1:8080:8080
    environment:
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      POSTGRES_URL: psql://admin:${POSTGRES_PASSWORD}@postgres:5432/admin

  app-test:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    container_name: app-test
    command: npm test
    restart: always
    volumes:
      - ./src:/opt/app/src
      - ./documents:/opt/app/documents
      - ./swagger.yaml:/opt/app/swagger.yaml
    environment:
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      POSTGRES_URL: psql://admin:${POSTGRES_PASSWORD}@postgres:5432/admin
