version: "3.8"
services:
  app-dev:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    container_name: app-dev
    command: npm run dev
    restart: always
    volumes:
      - ./src:/opt/app/src
      - ./documents:/opt/app/documents
      - ./swagger.yaml:/opt/app/swagger.yaml
    ports:
      - 127.0.0.1:8080:8080
