FROM node:lts-alpine as builder

LABEL maintainer="Flavien PERIER <perier@flavien.io>" \
      version="1.0.O" \
      description="Markdown API dev"

WORKDIR /opt/app
VOLUME /opt/app/documents
VOLUME /opt/app/src

COPY --chown=root:root . .

RUN npm install && \
    npm run build

EXPOSE 8080
