openapi: 3.0.1
info:
  version: 1.0.0
  title: markdown-api
  description: Markdown API
  termsOfService: https://github.com/flavien-perier/markdown-api/blob/master/LICENSE
  contact:
    email: perier@flavien.io
  license:
    name: MIT
    url: https://github.com/flavien-perier/markdown-api/blob/master/LICENSE

externalDocs:
  description: Readme
  url: https://github.com/flavien-perier/markdown-api/blob/master/README.md

servers:
- url: http://127.0.0.1:8080/

tags:
- name: Api
  description: Application

paths:          
  /:
    get:
      tags:
      - Api
      summary: File Search
      parameters:
      - name: p
        in: query
        required: false
        description: Page identifier
        schema:
          type: number
      - name: n
        in: query
        required: false
        description: Number of items per page
        schema:
          type: number
      - name: type
        in: query
        required: false
        description: Type of item to be returned
        schema:
          $ref: "#/components/schemas/ArticleType"
      - name: q
        in: query
        required: false
        description: Regex on the name of the article
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MarkdownHeader"
  
  /file/{fileName}:
    get:
      tags:
      - Api
      summary: Returns the file in markdown format
      parameters:
      - name: fileName
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            text/markdown:
              schema:
                type: string
                example: >
                  # Example of article
                  
                  You can visit my site [flavien.io](https://www.flavien.io/)
        404:
          description: NotFound

components:
  schemas:
    ArticleType:
      type: string
      description: Type of article
      enum:
      - ARTICLE
      - BLOG
      - DOCUMENTATION
  
    MarkdownHeader:
      type: object
      required:
      - title
      - author
      - date
      - url
      properties:
        title:
          type: string
          description: Title of the article
        type:
          $ref: "#/components/schemas/ArticleType"
        description: 
          type: string
          description: Description of the article
        author:
          type: string
          description: Author of the article
        date:
          type: string
          description: Date of publication of the article
          format: date-time
        url:
          type: string
          description: URL of the article